An array with a smaller shape is expanded to match the shape of a larger one. This is called broadcasting.

In [1]:
import numpy as np

# Create a 1D array
a = np.array([1, 2, 3])

# Create a scalar
b = 2

# Broadcasting allows us to perform arithmetic operations between arrays and scalars
c = a * b

print("Array a: ", a)
print("Scalar b: ", b)
print("Result of a * b: ", c)

Array a:  [1 2 3]
Scalar b:  2
Result of a * b:  [2 4 6]


In [8]:
import numpy as np

# create 1-D array
array1 = np.array([2, 3, 7])

# create 2-D array
array2 = np.array([[1], [5], [3]])

# adding arrays of different dimension
# size of array1 expands to match with array2
sum = array1 + array2

print(sum)

[[ 3  4  8]
 [ 7  8 12]
 [ 5  6 10]]


*Examples and rules from programiz*:

Every set of dimensions must be compatible with the arrays to be broadcastable. A set of dimension lengths is compatible when
1. one of them has a length of 1 or
2. they are equal

Broadcastable Shapes 
The folowing be arrray sizes:
(6, 7) and (6, 7);  cause 7=7 then 6=6
(6, 7) and (6, 1);  7 not equal to 1 but in either of them a 1 is present. and next set of dimension 6=6 
(6, 7) and (7, );   Rightmost in both arrays is 7, 7=7 and then goes to check 6 but there is nothing to compare with in 2nd array. still compatible.

*Two arrays need not have the same number of dimensions to be broadcastable.*

Non-Broadcastable Shapes

(6, 7) and (7, 6); 7 Not equal to 6 and 6 not equal to 7.
(6, 7) and (6, ); Rightmost set are 7 in 1st and 6 in 2nd array not equal thus not compatible.


For the example code above, array1 is 1D array and size (3,) and array2 is (3,1). The rightmost i.e 3,1 from those arrays respectively are not equal but one of them is 1 so compatible.
Next, make array1 to [[2, 3, 7]] a (1,3) size. This makes them compatible, now the addition of these make the result. In doing to array1 kind of expands to [[2, 3, 7], [2, 3, 7], [2, 3, 7]] (3, 3) size.