In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [5]:
import numpy as np
import timeit

n = int(input("Enter the number of rows (n): "))
k = int(input("Enter the number of columns (k): "))
m = int(input("Enter the number of columns (m): "))

# Initialize the matrix with zeros
matrix1 = [[0 for _ in range(k)] for _ in range(n)]
matrix2 = [[0 for _ in range(m)] for _ in range(k)]
matrix3 = [[0 for _ in range(m)] for _ in range(n)]

# Filling the matrix with input from the user
for i in range(n):
    matrix1[i] = list(map(int, input().split()))
    
for i in range(k):
    matrix2[i] = list(map(int, input().split()))

# Multiply the matrices
t1 = timeit.default_timer()
for i in range(n):
    for j in range(m):
        for a in range(k):
            matrix3[i][j] += matrix1[i][a]*matrix2[a][j]
t2 = timeit.default_timer()

# Print the result matrix
print(matrix3)
print((t2-t1)*10000)

M1 = np.array(matrix1)
M2 = np.array(matrix2)

# Multiply the matrices
t3 = timeit.default_timer()
result = np.dot(M1, M2)
t4 = timeit.default_timer()

# Print the result matrix
print(result)
print((t4-t3)*10000)


Enter the number of rows (n): 3
Enter the number of columns (k): 3
Enter the number of columns (m): 3
1 2 3
1 2 3
1 2 3
3 2 1
3 2 1
3 2 1
[[18, 12, 6], [18, 12, 6], [18, 12, 6]]
1.6289995983242989
[[18 12  6]
 [18 12  6]
 [18 12  6]]
1.0349997319281101


As we can see, it takes less time when used numpy np.dot(,) function than our normal matrix multiplication.
The difference in the timmings will be more wide and significant as the size of matrix increases. This is because the Numpy uses optimised libraries hence the operations are highly optimised and faster in nature. 

Also there is the case of solving a matrix in $$O(n^{\log_2 7})$$ which is faster than the $$O(n^3)$$ solution (1st method using 3 for loops nested).